title: Global Water Body Surface Area Atlas
description: A comprehensive polygon-based global water body atlas for biogeochemical budgeting
author: NguyenTruongAnLab

# GitHub Pages configuration
baseurl: "/estuary-type-map"
url: "https://nguyentruonganlab.github.io"

# Custom permalink style to ensure .md files become .html in output
permalink: pretty

# Markdown processing configuration - using GitHub Pages defaults
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

# Jekyll settings
highlighter: rouge

# Exclude large folders from Jekyll processing
exclude:
  - "data/processed/"
  - "data/raw/"
  - "scripts/"
  - "*.gpkg"
  - "*.nc"
  - "*.csv"
  - ".git/"
  - ".gitignore"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "ROADMAP.md"
  - "LICENSE"

# Include all Jekyll processing and site configuration files
include:
  - "_includes"
  - "_layouts"
  - "_data"
  # Removed .nojekyll as it prevents Jekyll processing
